#!/usr/bin/env node
/**
 * Apply a brand pack from brands/<id>/brand.json
 * Usage: BRAND=xiaoke node scripts/apply-brand.mjs
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { spawnSync } from "child_process";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const brandId = process.env.BRAND || "xiaonuo";
const brandDir = path.join(ROOT, "brands", brandId);
const brandPath = path.join(brandDir, "brand.json");

if (!fs.existsSync(brandPath)) {
  console.error(`[brand] Missing ${brandPath}`);
  process.exit(1);
}

/** @type {Record<string, unknown>} */
const brand = JSON.parse(fs.readFileSync(brandPath, "utf8"));

function writeJson(filePath, data) {
  fs.writeFileSync(filePath, `${JSON.stringify(data, null, 2)}\n`, "utf8");
}

function escapeRust(s) {
  return String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

// ─── Frontend runtime config ───────────────────────────────────────────────
const frontendBrand = {
  id: brand.id,
  displayNameZh: brand.displayNameZh,
  displayNameEn: brand.displayNameEn,
  productName: brand.productName,
  windowTitle: brand.windowTitle,
  overlayTitle: brand.overlayTitle,
  logoPath: brand.logoPath || "/piscis.png",
  i18nReplace: brand.i18nReplace || { zh: {}, en: {} },
  githubRepo: brand.githubRepo,
  bundleIdentifier: brand.bundleIdentifier,
};

writeJson(path.join(ROOT, "src/brand.generated.json"), frontendBrand);

// ─── Rust generated constants ────────────────────────────────────────────
const rustOut = path.join(ROOT, "src-tauri/src/brand_generated.rs");
const rustSrc = `// Auto-generated by scripts/apply-brand.mjs — do not edit.
// Active brand: ${brand.id}
#![allow(dead_code)]

pub const BRAND_ID: &str = "${escapeRust(brand.id)}";
pub const PRODUCT_NAME: &str = "${escapeRust(brand.productName)}";
pub const DISPLAY_NAME_ZH: &str = "${escapeRust(brand.displayNameZh)}";
pub const DISPLAY_NAME_EN: &str = "${escapeRust(brand.displayNameEn)}";
pub const PRO_WINDOW_TITLE: &str = "${escapeRust(brand.proWindowTitle)}";
pub const GITHUB_REPO: &str = "${escapeRust(brand.githubRepo)}";
`;
fs.writeFileSync(rustOut, rustSrc, "utf8");

// ─── Tauri bundle metadata ─────────────────────────────────────────────────
const tauriPath = path.join(ROOT, "src-tauri/tauri.conf.json");
const tauri = JSON.parse(fs.readFileSync(tauriPath, "utf8"));
tauri.productName = brand.productName;
if (brand.bundleIdentifier) {
  tauri.identifier = brand.bundleIdentifier;
}
if (tauri.app?.windows?.[0]) {
  tauri.app.windows[0].title = brand.windowTitle;
}
if (tauri.app?.windows?.[1]) {
  tauri.app.windows[1].title = brand.overlayTitle;
}
if (tauri.bundle) {
  tauri.bundle.copyright = brand.copyright;
  tauri.bundle.shortDescription = brand.shortDescription;
  tauri.bundle.longDescription = brand.longDescription;
}
writeJson(tauriPath, tauri);

// ─── index.html title ──────────────────────────────────────────────────────
const indexPath = path.join(ROOT, "index.html");
let indexHtml = fs.readFileSync(indexPath, "utf8");
indexHtml = indexHtml.replace(/<title>[^<]*<\/title>/, `<title>${brand.windowTitle}</title>`);
fs.writeFileSync(indexPath, indexHtml, "utf8");

// ─── Icons (optional) ──────────────────────────────────────────────────────
const iconSource = path.join(ROOT, brand.iconSource || "");
if (iconSource && fs.existsSync(iconSource)) {
  console.log(`[brand] Generating icons from ${brand.iconSource}`);
  const heroSource = path.join(ROOT, brand.chatEmptyHeroSource || "");
  const pyArgs = ["scripts/make_icons.py", "--source", iconSource];
  if (heroSource && fs.existsSync(heroSource)) {
    pyArgs.push("--hero", heroSource);
  }
  const py = spawnSync("python3", pyArgs, {
    cwd: ROOT,
    stdio: "inherit",
  });
  if (py.status !== 0) {
    console.warn("[brand] Icon generation failed (non-fatal)");
  }
} else {
  console.log(`[brand] No icon source at ${brand.iconSource || "(none)"} — skipping icon generation`);
}

// ─── Active brand marker (for debugging) ───────────────────────────────────
fs.writeFileSync(path.join(ROOT, ".brand-active"), `${brand.id}\n`, "utf8");

console.log(`[brand] Applied "${brand.id}" (${brand.displayNameZh} / ${brand.displayNameEn})`);
