// Auto-generated by scripts/apply-brand.mjs — do not edit.
// Active brand: baozi
#![allow(dead_code)]

pub const BRAND_ID: &str = "baozi";
pub const PRODUCT_NAME: &str = "9X bot";
pub const DISPLAY_NAME_ZH: &str = "包子";
pub const DISPLAY_NAME_EN: &str = "Baozi";
pub const PRO_WINDOW_TITLE: &str = "9X bot · 专业功能";
pub const GITHUB_REPO: &str = "njbinbin/openpisci";
